paths:
  /products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Lista de productos paginada
        "500":
          description: Hubo un error
    post:
      summary: Crear un producto
      tags:
        - Products
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/createProduct"
      responses:
        "200":
          description: Producto creado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "401":
          description: "Acceso solo para Usuarios Premiun."       
  /products/{pid}:
    get:
      summary: Obtener un producto por id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: 'Parametro para identificar el producto'
        schema:
          $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: "Hubo un error"
        "404":
          description: "No existe el producto"  
    put: 
      summary: Actualizar datos de un producto por id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: 'Parametro para identificar el producto'
        schema:
          $type: String
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/updateProduct"    
      responses:
        "200":
          description: Producto actualizado
        "401":
          description: "Esta accion es solo para Administradores y usuarios Premiun."       
        "402":
          description: "Solo puede realizar esta accion en productos propios."     
        "404":
          description: "No existe el producto."       
    delete: 
      summary: Eliminar un producto por id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: 'Parametro para identificar el producto'
        schema:
          $type: String
      responses:
        "200":
          description: Producto eliminado
        "401":
          description: "Esta accion es solo para Administradores y usuarios Premiun."       
        "402":
          description: "Solo puede realizar esta accion en productos propios."     
        "404":
          description: "No existe el producto."

components:
  schemas:
    Product:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: Id autogenerado por mongo
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: Descripcion del producto
        code: 
          type: String
          description: Code autogenerado por uuid
        category: 
          type: String
          description: Categoria del producto      
        price: 
          type: String
          description: Precio del producto
        stock: 
          type: Integer
          description: Stock del producto
      example:
        _id: ObjectId("64ed77833f395404ac887f75")
        title: Mayonesa Hellmans
        description: 500gr
        code: "fff4c670-4625-11ee-8b63-052728d9702f"
        category: Alimentos
        price: "500"
        stock: 200
    createProduct:
      type: object
      properties:
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: Descripcion del producto
        category: 
          type: String
          description: Categoria del producto      
        price: 
          type: String
          description: Precio del producto
        stock: 
          type: Integer
          description: Stock del producto
      example:
        title: Mayonesa Hellmans
        description: 500gr
        category: Alimentos
        price: "500"
        stock: 200
    updateProduct:
      type: object
      properties:
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: Descripcion del producto
        category: 
          type: String
          description: Categoria del producto      
        price: 
          type: String
          description: Precio del producto
        stock: 
          type: Integer
          description: Stock del producto
      example:
        title: Mayonesa Hellmans
        description: 500gr
        category: Alimentos
        price: "500"
        stock: 200

      
      
      

        